#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/cltd.h"
#include "data-mov/leave.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"

#include "zjtadd/push.h"
#include "zjtadd/call.h"
#include "zjtadd/test.h"
#include "zjtadd/je.h"
#include "zjtadd/pop.h"
#include "zjtadd/ret.h"
#include "zjtadd/add.h"
#include "zjtadd/cmp.h"
#include "zjtadd/sub.h"
#include "zjtadd/sbb.h"
#include "zjtadd/jmp.h"
#include "zjtadd/jbe.h"
#include "zjtadd/jle.h"
#include "zjtadd/jl.h"
#include "zjtadd/ja.h"
#include "zjtadd/jg.h"
#include "zjtadd/js.h"
#include "zjtadd/jns.h"
#include "zjtadd/jge.h"
#include "zjtadd/jne.h"
#include "zjtadd/lea.h"
#include "zjtadd/adc.h"
#include "zjtadd/movs.h"
#include "zjtadd/setne.h"
#include "zjtadd/lods.h"
#include "zjtadd/scas.h"
#include "zjtadd/stos.h"
#include "zjtadd/movzb.h"
#include "zjtadd/movsb.h"
#include "zjtadd/movsw.h"
#include "zjtadd/movzw.h"
