#include "prefix/prefix.h"
//#include "cmp/cmp.h"

#include "contrain/call.h"
#include "contrain/je.h"
#include "contrain/jmp.h"
#include "contrain/jbe.h"
#include  "contrain/jne.h"
#include "contrain/jge.h"
#include  "contrain/jl.h"
#include "contrain/ja.h"
#include "contrain/jle.h"
#include "contrain/jg.h"
#include "contrain/jo.h"
#include "contrain/jno.h"
#include "contrain/jb.h"
#include "contrain/jae.h"
#include "contrain/js.h"
#include "contrain/jns.h"
#include "contrain/jp.h"
#include "contrain/jnp.h"
#include "contrain/ret.h"


#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/movext.h"
#include "data-mov/pop.h"
#include "data-mov/push.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "arith/sbb.h"
#include "arith/sub.h"
#include "arith/cmp.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/sete.h"
#include "logic/setne.h"
#include "logic/test.h"
#include "string/rep.h"
#include "misc/misc.h"
#include "cl/clc.h"
#include "special/special.h"